services:
  #  MySQL Database service
  db:
    image: mysql:8.0
    container_name: deliverymatch-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliveryMatchDB
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # service
  backend:
    build: .
    container_name: deliverymatch-backend
    ports:
      - "8887:8888"
    depends_on:
      - db
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/deliveryMatchDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: